//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamPoweredTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamPoweredTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Config&gt;
        ///	&lt;WebBrowser name=&quot;Firefox&quot;/&gt;
        ///	&lt;WebAdress url=&quot;http://store.steampowered.com/&quot;/&gt;
        ///	&lt;ImplicitWait hours=&quot;0&quot; minutes=&quot;0&quot; seconds=&quot;30&quot; /&gt;
        ///	&lt;PageLoad hours=&quot;0&quot;  minutes=&quot;1&quot; seconds=&quot;0&quot;/&gt;
        ///	&lt;WebDriverWait hours=&quot;0&quot;  minutes=&quot;0&quot; seconds=&quot;30&quot;/&gt;
        ///	&lt;DownloadTimer seconds=&quot;60&quot;/&gt;
        ///	&lt;DownloadsPath Chrome=&quot;chrome://downloads/&quot; Firefox=&quot;about:downloads&quot;/&gt;
        ///&lt;/Config&gt;.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Data&gt;
        ///	&lt;Category ru=&quot;Игры&quot; en=&quot;Games&quot;/&gt;
        ///	&lt;Item ru=&quot;Экшен&quot; en=&quot;Action&quot;/&gt;
        ///	&lt;TabPanelItem ru=&quot;Скидки&quot; en=&quot;Specials&quot;/&gt;
        ///	&lt;AgeInput ru=&quot;Пожалуйста, введите дату вашего рождения:&quot; en=&quot;Please enter your birth date to continue:&quot;/&gt;
        ///	&lt;AgeConfirm ru=&quot;Содержимое этого товара может не подходить всем возрастам, а его просмотр на работе может быть недопустим.&quot;
        ///				en=&quot;Content in this product may not be appropriate for all ages, or may not be appropriate for viewing at work.&quot;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Data&gt;
        ///	&lt;ValidAge day=&quot;1&quot; month=&quot;January&quot; year=&quot;1985&quot; /&gt;	
        ///&lt;/Data&gt;.
        /// </summary>
        internal static string ValidData {
            get {
                return ResourceManager.GetString("ValidData", resourceCulture);
            }
        }
    }
}
